### ISSUE TITLE
'xdebug.hash'

### ISSUE THREAD

**Issue by astridx** [joomla-projects/virtualisation#5]
When I use 

```
		$generator = new DockerComposeGenerator('tests/fixtures');
		$generator->write('dockyard/docker-compose.yml');
```
I got an error.

After changing (xdebug.hash)

```
		$dockerTemplate->setVariables(
			[
				'php.filename'    => $php['filename'],
				'php.version'     => $phpInfo['version'],
				'php.url'         => $phpUrl,
				'php.asc.url'     => $phpAscUrl,
				'php.md5'         => $php['md5'],
				'php.sha256'      => $php['sha256'],
				'php.patches'     => '', // implode(' ', $this->findPatches($dockerPath, $phpInfo['version'])),
				'gpg.keys'        => '""', // $this->getGpgKeys($phpInfo['gpg']),
				'xdebug.version'  => $phpInfo['xdebug']['version'],
				'xdebug.hashtype' => 'sha256',
				'xdebug.hash'     => $phpInfo['xdebug']['sha256'],
			]


```
into 

```
		$dockerTemplate->setVariables(
			[
				'php.filename'    => $php['filename'],
				'php.version'     => $phpInfo['version'],
				'php.url'         => $phpUrl,
				'php.asc.url'     => $phpAscUrl,
				'php.md5'         => $php['md5'],
				'php.sha256'      => $php['sha256'],
				'php.patches'     => '', // implode(' ', $this->findPatches($dockerPath, $phpInfo['version'])),
				'gpg.keys'        => '""', // $this->getGpgKeys($phpInfo['gpg']),
				'xdebug.version'  => $phpInfo['xdebug']['version'],
				'xdebug.hashtype' => 'sha256',
				'xdebug.hash'     => '""', //$phpInfo['xdebug']['sha256'],
			]


```
in the file ../virtualisation/src/Service/PhpBase.php
I could create files successfully with the above commands
```
		$generator = new DockerComposeGenerator('tests/fixtures');
		$generator->write('dockyard/docker-compose.yml');
```
Xdebug is configured on my machine. Do I make a mistake or is there a problem with this variable?

**Comment by nibra** [comment]
Since the composer dependancies were updated, you need to do another `composer install`.
The XDebug version was not present for the newest PHP.

However, I started changing to use the official PHP images (that means just no ancient versions). They need another way to install XDebug. So don't invest too much time into debugging this ;)

**Comment by astridx** [comment]
I did composer install.

Do I understand you right? It is not a problem of my machine if I get error messages when I run the tests:

```
vendor/bin/phpunit
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.18-1+deb.sury.org~xenial+1 with Xdebug 2.5.1
Configuration: /home/astrid/docker/joomla/virtualisation/phpunit.xml.dist

E....E........F.E.......                                          24 / 24 (100%)

Time: 1.1 seconds, Memory: 8.00MB

There were 3 errors:

1) Joomla\Tests\Virtualisation\DockerComposeGeneratorTest::testTheGeneratedFileContainsCorrectBuildInstructions
Undefined index: sha256

/home/astrid/docker/joomla/virtualisation/src/Service/PhpBase.php:60
/home/astrid/docker/joomla/virtualisation/src/Service/Apache.php:75
/home/astrid/docker/joomla/virtualisation/src/DockerComposeGenerator.php:57
/home/astrid/docker/joomla/virtualisation/src/DockerComposeGenerator.php:37
/home/astrid/docker/joomla/virtualisation/tests/DockerComposeGeneratorTest.php:19

2) Joomla\Tests\Virtualisation\Service\ApacheTest::testFilesystemIsSetUp
Undefined index: sha256

/home/astrid/docker/joomla/virtualisation/src/Service/PhpBase.php:60
/home/astrid/docker/joomla/virtualisation/src/Service/Apache.php:75
/home/astrid/docker/joomla/virtualisation/tests/Service/ApacheTest.php:55

3) Joomla\Tests\Virtualisation\Service\PhpFpmTest::testFilesystemIsSetUp
Undefined index: sha256

/home/astrid/docker/joomla/virtualisation/src/Service/PhpBase.php:60
/home/astrid/docker/joomla/virtualisation/src/Service/PhpFpm.php:62
/home/astrid/docker/joomla/virtualisation/tests/Service/PhpFpmTest.php:51

--

There was 1 failure:

1) Joomla\Tests\Virtualisation\Service\NginxTest::testFilesystemIsSetUp
Failed asserting that file "dockyard/docker/nginx-1.9/conf/j3-postgresql.dev/vhost.conf" exists.

/home/astrid/docker/joomla/virtualisation/tests/Service/ServiceTestCase.php:21
/home/astrid/docker/joomla/virtualisation/tests/Service/NginxTest.php:60

ERRORS!
Tests: 24, Assertions: 28, Errors: 3, Failures: 1.

```
The problem is that xdebug is not supported in the official PHP image ?

**Comment by nibra** [comment]
Seems like you still have an old version of PhpVersions (a dependancy). Try to remove its cache:

    $ rm ~/.php_versions

The code in the repo does not yet use the official images. I'm still working on that. In the meantime, you can use your 'xdebug.hash' fix.
The Failure, though, was a bug in the test itself. That's fixed.

**Comment by astridx** [comment]
It maybe that I get on your nerves, but :)

First:  I am sure, that I deleted the file ~/.php_verisons. It was in my home directory. And after deleting I did not see it with `ls -a `any more.

This evening
1. I pulled the current version of the master branch. 
2. Then I deleted the file `~/.php_versions` again.
3. It was possible for me to run all tests successfully. 
4. Then I used the created dockeryard-folder for the command `docker-compose up `
But I ended with this error:

```

$ docker-compose up
dockyard_postgresqlvlatest_1 is up-to-date
dockyard_mysqlvlatest_1 is up-to-date
Starting dockyard_proxy_1
Creating dockyard_apachev5p4_1
Creating dockyard_phpvlatest_1
Creating dockyard_phpv5p4_1

ERROR: for phpvlatest  Cannot create container for service phpvlatest: create docker/nginx-1.8/html/j3-postgresql-18.dev: "docker/nginx-1.8/html/j3-postgresql-18.dev" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path

ERROR: for phpv5p4  Cannot create container for service phpv5p4: create docker/apache-5.4/html/j25-mysqli.dev: "docker/apache-5.4/html/j25-mysqli.dev" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path

ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint dockyard_proxy_1 (8eb499c35d369b433097ec78abae946f0b809cbd4f2f6441923118e84de8e84a): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use

ERROR: for apachev5p4  Cannot create container for service apachev5p4: create docker/apache-5.4/conf: "docker/apache-5.4/conf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path
ERROR: Encountered errors while bringing up the project.

```

After making all volume paths absolute and changing the port for the proxy to 81 - because I am runnning apache on this port - I could succeed with

`docker-compse up`

- - - 


This is my changed docker-compse.yml

```
proxy:
  image: 'jwilder/nginx-proxy:alpine'
  ports:
    - '81:80'
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
apachev5p4:
  build: docker/apache-5.4
  volumes:
    - '/home/astrid/docker/apache-5.4/conf:/etc/apache2/sites-enabled'
    - '/home/astrid/docker/apache-5.4/html:/var/www/html'
    - '/home/astrid/docker/joomla/virtualisation/vendor:/usr/local/lib/php/vendor'
  links:
    - mysqlvlatest
  environment:
    VIRTUAL_HOST: j25-mysqli.dev
mysqlvlatest:
  image: 'mariadb:latest'
  volumes:
    - 'mysql-latest:/docker-entrypoint-initdb.d'
  environment:
    MYSQL_DATABASE: joomla_test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: sqladmin
    MYSQL_PASSWORD: sqladmin
phpv5p4:
  build: docker/php-5.4
  volumes:
    - '/home/astrid/docker/joomla/virtualisation/vendor:/usr/local/lib/php/vendor'
    - '/home/astrid/docker/apache-5.4/html/j25-mysqli.dev:/var/www/html/j25-mysqli.dev'
  links:
    - mysqlvlatest
nginxv1p9:
  image: 'nginx:1.9'
  volumes:
    - '/home/astrid/docker/joomla/virtualisation/vendor:/usr/local/lib/php/vendor'
    - '/home/astrid/docker/nginx-1.9/conf:/etc/nginx/conf.d'
    - '/home/astrid/docker/nginx-1.9/html/j3-postgresql-19.dev:/var/www/html/j3-postgresql-19.dev'
  links:
    - phpvlatest
  environment:
    VIRTUAL_HOST: j3-postgresql-19.dev
postgresqlvlatest:
  image: 'postgres:latest'
  volumes:
    - 'postgresql-latest:/docker-entrypoint-initdb.d'
  environment:
    POSTGRES_DB: joomla_test
    POSTGRES_USER: sqladmin
    POSTGRES_PASSWORD: sqladmin
phpvlatest:
  build: docker/php-latest
  volumes:
    - '/home/astrid/docker/joomla/virtualisation/vendor:/usr/local/lib/php/vendor'
    - '/home/astrid/docker/nginx-1.9/html/j3-postgresql-19.dev:/var/www/html/j3-postgresql-19.dev'
    - '/home/astrid/docker/nginx-1.8/html/j3-postgresql-18.dev:/var/www/html/j3-postgresql-18.dev'
  links:
    - postgresqlvlatest
nginxv1p8:
  image: 'nginx:1.8'
  volumes:
    - '/home/astrid/docker/joomla/virtualisation/vendor:/usr/local/lib/php/vendor'
    - '/home/astrid/docker/nginx-1.8/conf:/etc/nginx/conf.d'
    - '/home/astrid/docker/nginx-1.8/html/j3-postgresql-18.dev:/var/www/html/j3-postgresql-18.dev'
  links:
    - phpvlatest
  environment:
    VIRTUAL_HOST: j3-postgresql-18.dev

```


So for me there is a happy end :)
Could/Should I close this issue?
